In [56]:
import pandas as pd
import numpy as np

dat = pd.read_csv('lineups_with_clusters.csv')
dat.head(5)

GROUP_SET                                   GROUP_ID  \
0   Lineups      -201145-203115-203932-203999-1628420-   
1   Lineups    -101108-203109-1626164-1628969-1629028-   
2   Lineups     -201144-202711-203497-1626220-1628378-   
3   Lineups    -201143-203935-1627759-1628369-1629057-   
4   Lineups   -201976-1626156-1626157-1629020-1630162-   

                                          GROUP_NAME     TEAM_ID  \
0   J. Green - W. Barton - A. Gordon - N. Jokic -...  1610612743   
1   C. Paul - J. Crowder - D. Booker - M. Bridges...  1610612756   
2   M. Conley - B. Bogdanovic - R. Gobert - R. O'...  1610612762   
3   A. Horford - M. Smart - J. Brown - J. Tatum -...  1610612738   
4   P. Beverley - D. Russell - K. Towns - J. Vand...  1610612750   

   TEAM_ABBREVIATION   GP   W   L   W_PCT    MIN  ...           p1  \
0                DEN   41  26  15   0.634  761.0  ...     J. Green   
1                PHO   38  31   7   0.816  754.0  ...      C. Paul   
2                UTA   42  29  13   0.690  666.0  ...    M. Conley   
3                BOS   34  27   7   0.794  443.0  ...   A. Horford   
4                MIN   36  22  14   0.611  439.0  ...  P. Beverley   

              p2         p3             p4               p5  p1_cluster  \
0      W. Barton  A. Gordon       N. Jokic        M. Morris           2   
1     J. Crowder  D. Booker     M. Bridges         D. Ayton           1   
2  B. Bogdanovic  R. Gobert     R. O'Neale      D. Mitchell           3   
3       M. Smart   J. Brown       J. Tatum  R. Williams III           5   
4     D. Russell   K. Towns  J. Vanderbilt       A. Edwards           3   

   p2_cluster  p3_cluster  p4_cluster  p5_cluster  
0           3           3           1           3  
1           0           1           3           5  
2           3           5           0           1  
3           3           1           1           0  
4           1           1           5           3  

[5 rows x 58 columns]

In [57]:
dat_selected = dat.loc[:, [' NET_RATING', ' MIN', 'p1_cluster', 'p2_cluster', 'p3_cluster', 'p4_cluster', 'p5_cluster']]

In [58]:
dat_selected

NET_RATING    MIN  p1_cluster  p2_cluster  p3_cluster  p4_cluster  \
0             9.5  761.0           2           3           3           1   
1             7.4  754.0           1           0           1           3   
2             6.7  666.0           3           3           5           0   
3            24.6  443.0           5           3           1           1   
4            12.8  439.0           3           1           1           5   
...           ...    ...         ...         ...         ...         ...   
1995         23.1   12.0           6           3           5           2   
1996        -34.3   12.0           2           3           0           1   
1997         49.3   12.0           2           7           0           0   
1998          0.4   12.0           5           7           3           3   
1999         -4.4   12.0           5           1           6           6   

      p5_cluster  
0              3  
1              5  
2              1  
3              0  
4              3  
...          ...  
1995           0  
1996           3  
1997           6  
1998           6  
1999           0  

[2000 rows x 7 columns]

In [59]:
for i in range(5):
    print(dat_selected[f'p{i+1}_cluster'].unique())

[2 1 3 5 0 6 7]
[3 0 1 5 6 7 2]
[3 1 5 0 6 2 7]
[1 3 0 5 6 2 7 4]
[3 5 1 0 6 7 2 4]


In [60]:
3 + np.nan

nan

In [61]:
total_dummies = pd.DataFrame(np.zeros((dat_selected.shape[0], 8)))
dummies_no4 = pd.DataFrame(np.zeros((dat_selected.shape[0], 8)))
dummies_4 = pd.DataFrame(np.zeros((dat_selected.shape[0], 8)))
for i in range(3):
    dummies_no4 += pd.get_dummies(dat_selected[f'p{i+1}_cluster'], dummy_na=True)

for i in range(2):
    dummies_4 += pd.get_dummies(dat_selected[f'p{i+4}_cluster'], dummy_na=True)

dummies_no4.fillna(0, inplace=True)
total_dummies = dummies_no4 + dummies_4

In [62]:
total_dummies

0    1    2    3    4    5    6    7
0     0.0  1.0  1.0  3.0  0.0  0.0  0.0  0.0
1     1.0  2.0  0.0  1.0  0.0  1.0  0.0  0.0
2     1.0  1.0  0.0  2.0  0.0  1.0  0.0  0.0
3     1.0  2.0  0.0  1.0  0.0  1.0  0.0  0.0
4     0.0  2.0  0.0  2.0  0.0  1.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...
1995  1.0  0.0  1.0  1.0  0.0  1.0  1.0  0.0
1996  1.0  1.0  1.0  2.0  0.0  0.0  0.0  0.0
1997  2.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0
1998  0.0  0.0  0.0  2.0  0.0  1.0  1.0  1.0
1999  1.0  1.0  0.0  0.0  0.0  1.0  2.0  0.0

[2000 rows x 8 columns]

In [63]:
total_dummies.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64

In [64]:
dat_final = pd.concat([dat_selected.loc[:, [' NET_RATING', ' MIN']], total_dummies], axis=1)

In [65]:
dat_final.columns

Index([' NET_RATING', ' MIN', 0, 1, 2, 3, 4, 5, 6, 7], dtype='object')

In [66]:
dat_final.rename(columns={' NET_RATING': 'net_rating', " MIN": 'minutes', 0: 'cluster_0', 1: 'cluster_1', 2: 'cluster_2', 3: 'cluster_3', 4: 'cluster_4', 5: 'cluster_5', 6: 'cluster_6', 7: 'cluster_7',}, inplace=True)
dat_final

net_rating  minutes  cluster_0  cluster_1  cluster_2  cluster_3  \
0            9.5    761.0        0.0        1.0        1.0        3.0   
1            7.4    754.0        1.0        2.0        0.0        1.0   
2            6.7    666.0        1.0        1.0        0.0        2.0   
3           24.6    443.0        1.0        2.0        0.0        1.0   
4           12.8    439.0        0.0        2.0        0.0        2.0   
...          ...      ...        ...        ...        ...        ...   
1995        23.1     12.0        1.0        0.0        1.0        1.0   
1996       -34.3     12.0        1.0        1.0        1.0        2.0   
1997        49.3     12.0        2.0        0.0        1.0        0.0   
1998         0.4     12.0        0.0        0.0        0.0        2.0   
1999        -4.4     12.0        1.0        1.0        0.0        0.0   

      cluster_4  cluster_5  cluster_6  cluster_7  
0           0.0        0.0        0.0        0.0  
1           0.0        1.0        0.0        0.0  
2           0.0        1.0        0.0        0.0  
3           0.0        1.0        0.0        0.0  
4           0.0        1.0        0.0        0.0  
...         ...        ...        ...        ...  
1995        0.0        1.0        1.0        0.0  
1996        0.0        0.0        0.0        0.0  
1997        0.0        0.0        1.0        1.0  
1998        0.0        1.0        1.0        1.0  
1999        0.0        1.0        2.0        0.0  

[2000 rows x 10 columns]

In [67]:
dat_final.describe()

net_rating      minutes    cluster_0    cluster_1    cluster_2  \
count  2000.00000  2000.000000  2000.000000  2000.000000  2000.000000   
mean      2.03165    35.133000     1.398500     0.799500     0.352000   
std      25.70921    51.677874     0.918215     0.699675     0.551587   
min    -112.50000    12.000000     0.000000     0.000000     0.000000   
25%     -13.90000    15.000000     1.000000     0.000000     0.000000   
50%       2.70000    21.000000     1.000000     1.000000     0.000000   
75%      18.70000    34.000000     2.000000     1.000000     1.000000   
max      90.30000   761.000000     5.000000     3.000000     3.000000   

         cluster_3    cluster_4    cluster_5    cluster_6    cluster_7  
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  
mean      1.155500     0.001000     0.607000     0.449000     0.237500  
std       0.883012     0.031615     0.585425     0.579281     0.528425  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.750000     0.000000     0.000000     0.000000     0.000000  
50%       1.000000     0.000000     1.000000     0.000000     0.000000  
75%       2.000000     0.000000     1.000000     1.000000     0.000000  
max       4.000000     1.000000     2.000000     2.000000     4.000000

In [68]:
min_50 = dat_final.loc[dat_final['minutes'] >= 50, :]

In [69]:
len(min_50)

286

## Start with Linear Regression

In [70]:
import statsmodels.formula.api as smf
from sklearn.model_selection import train_test_split

X = dat_final.drop(labels=['net_rating'], axis=1)
y = dat_final['net_rating']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
formula = 'net_rating ~ cluster_0 + cluster_1 + cluster_2 + cluster_3 + cluster_4 + cluster_5 + cluster_6 + cluster_7'
m1 = smf.ols(formula=formula, data = pd.concat([X_train, y_train], axis = 1))
m1_fit = m1.fit()
m1_fit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:             net_rating   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     2.334
Date:                Tue, 07 Mar 2023   Prob (F-statistic):             0.0228
Time:                        12:34:39   Log-Likelihood:                -6256.4
No. Observations:                1340   AIC:                         1.253e+04
Df Residuals:                    1332   BIC:                         1.257e+04
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -2.122e+14   2.33e+14     -0.912      0.362   -6.68e+14    2.44e+14
cluster_0   4.243e+13   4.65e+13      0.912      0.362   -4.88e+13    1.34e+14
cluster_1   4.243e+13   4.65e+13      0.912      0.362   -4.88e+13    1.34e+14
cluster_2   4.243e+13   4.65e+13      0.912      0.362   -4.88e+13    1.34e+14
cluster_3   4.243e+13   4.65e+13      0.912      0.362   -4.88e+13    1.34e+14
cluster_4   4.243e+13   4.65e+13      0.912      0.362   -4.88e+13    1.34e+14
cluster_5   4.243e+13   4.65e+13      0.912      0.362   -4.88e+13    1.34e+14
cluster_6   4.243e+13   4.65e+13      0.912      0.362   -4.88e+13    1.34e+14
cluster_7   4.243e+13   4.65e+13      0.912      0.362   -4.88e+13    1.34e+14
==============================================================================
Omnibus:                       19.091   Durbin-Watson:                   2.041
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               25.491
Skew:                          -0.172   Prob(JB):                     2.91e-06
Kurtosis:                       3.581   Cond. No.                     9.17e+14
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.37e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [71]:
# LR for >50 minutes

min_50 = dat_final.loc[dat_final['minutes'] >= 50, :]
X = min_50.drop(labels=['net_rating'], axis=1)
y = min_50['net_rating']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
formula = 'net_rating ~ cluster_0 + cluster_1 + cluster_2 + cluster_3 + cluster_4 + cluster_5 + cluster_6 + cluster_7'
m1 = smf.ols(formula=formula, data = pd.concat([X_train, y_train], axis = 1))
m1_fit = m1.fit()
m1_fit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:             net_rating   R-squared:                       0.091
Model:                            OLS   Adj. R-squared:                  0.061
Method:                 Least Squares   F-statistic:                     3.065
Date:                Tue, 07 Mar 2023   Prob (F-statistic):            0.00698
Time:                        12:34:39   Log-Likelihood:                -766.99
No. Observations:                 191   AIC:                             1548.
Df Residuals:                     184   BIC:                             1571.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.9819      0.702     -1.399      0.163      -2.367       0.403
cluster_0     -0.4804      0.982     -0.489      0.625      -2.419       1.458
cluster_1      3.2932      1.134      2.905      0.004       1.057       5.530
cluster_2     -4.6257      2.275     -2.033      0.043      -9.115      -0.137
cluster_3     -0.1175      0.886     -0.133      0.895      -1.866       1.631
cluster_4   7.803e-17   3.01e-16      0.259      0.796   -5.16e-16    6.72e-16
cluster_5      2.6724      1.611      1.659      0.099      -0.507       5.851
cluster_6     -1.8644      2.122     -0.878      0.381      -6.052       2.323
cluster_7     -3.7870      3.979     -0.952      0.343     -11.638       4.064
==============================================================================
Omnibus:                        1.396   Durbin-Watson:                   1.995
Prob(Omnibus):                  0.498   Jarque-Bera (JB):                1.415
Skew:                          -0.203   Prob(JB):                        0.493
Kurtosis:                       2.887   Cond. No.                     5.42e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.16e-33. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [72]:
import statistics as stat

pred = m1_fit.predict(X_test)
mse = np.mean((pred - y_test)**2)
r2 = 1 - mse / stat.variance(y_test)
r2

-0.031228031374119558

In [73]:
pred = m1_fit.predict(X_test)
mae = np.mean(abs(pred - y_test))
mae

10.91318099137162

Pretty poor, so not going to waste time doing testing or cross validation

# Try xgboost

In [74]:
from xgboost import XGBRegressor
from sklearn.model_selection import cross_val_score

X = min_50.drop(labels=['net_rating'], axis=1)
y = min_50['net_rating']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
m2 = XGBRegressor()
m2.fit(X_train, y_train)

scores_mae = cross_val_score(m2, X_train, y_train,scoring='neg_mean_absolute_error', cv= 10)
-scores_mae.mean()

14.575804619922451

In [75]:
scores_r2 = cross_val_score(m2, X_train, y_train,scoring='r2', cv= 10)
scores_r2.mean()

-0.6511144306581933

## Try Random Forest

Always the best

In [76]:
from sklearn.ensemble import RandomForestRegressor

# Build basic model to see if it is worth doing grid search to find best params
X = min_50.drop(labels=['net_rating'], axis=1)
y = min_50['net_rating']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
rf = RandomForestRegressor(n_estimators = 30, random_state = 42, oob_score=True)
rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=30, oob_score=True, random_state=42)

In [77]:
len(X_train)

191

In [78]:
rf.score(X_train, y_train)

0.8252368957623246

In [79]:
rf.oob_score_

-0.1587623684506012

In [80]:
pred = rf.predict(X_test)
mae = np.mean(abs(pred - y_test))
mae

12.301134502923974

In [81]:
import statistics as stat

mse = np.mean((pred - y_test)**2)
r2 = 1 - mse / stat.variance(y_test)
r2

-0.23281454143821523