In [16]:
import pandas as pd
import numpy as np

dat = pd.read_csv('lineups_with_clusters.csv')
dat.head(5)

GROUP_SET                                   GROUP_ID  \
0   Lineups      -201145-203115-203932-203999-1628420-   
1   Lineups    -101108-203109-1626164-1628969-1629028-   
2   Lineups     -201144-202711-203497-1626220-1628378-   
3   Lineups    -201143-203935-1627759-1628369-1629057-   
4   Lineups   -201976-1626156-1626157-1629020-1630162-   

                                          GROUP_NAME     TEAM_ID  \
0   J. Green - W. Barton - A. Gordon - N. Jokic -...  1610612743   
1   C. Paul - J. Crowder - D. Booker - M. Bridges...  1610612756   
2   M. Conley - B. Bogdanovic - R. Gobert - R. O'...  1610612762   
3   A. Horford - M. Smart - J. Brown - J. Tatum -...  1610612738   
4   P. Beverley - D. Russell - K. Towns - J. Vand...  1610612750   

   TEAM_ABBREVIATION   GP   W   L   W_PCT    MIN  ...           p1  \
0                DEN   41  26  15   0.634  761.0  ...     J. Green   
1                PHO   38  31   7   0.816  754.0  ...      C. Paul   
2                UTA   42  29  13   0.690  666.0  ...    M. Conley   
3                BOS   34  27   7   0.794  443.0  ...   A. Horford   
4                MIN   36  22  14   0.611  439.0  ...  P. Beverley   

              p2         p3             p4               p5  p1_cluster  \
0      W. Barton  A. Gordon       N. Jokic        M. Morris           2   
1     J. Crowder  D. Booker     M. Bridges         D. Ayton           1   
2  B. Bogdanovic  R. Gobert     R. O'Neale      D. Mitchell           3   
3       M. Smart   J. Brown       J. Tatum  R. Williams III           5   
4     D. Russell   K. Towns  J. Vanderbilt       A. Edwards           3   

   p2_cluster  p3_cluster  p4_cluster  p5_cluster  
0           3           3           1           3  
1           0           1           3           5  
2           3           5           0           1  
3           3           1           1           0  
4           1           1           5           3  

[5 rows x 58 columns]

In [17]:
dat_selected = dat.loc[:, [' NET_RATING', 'p1_cluster', 'p2_cluster', 'p3_cluster', 'p4_cluster', 'p5_cluster']]

In [18]:
dat_selected

NET_RATING  p1_cluster  p2_cluster  p3_cluster  p4_cluster  p5_cluster
0             9.5           2           3           3           1           3
1             7.4           1           0           1           3           5
2             6.7           3           3           5           0           1
3            24.6           5           3           1           1           0
4            12.8           3           1           1           5           3
...           ...         ...         ...         ...         ...         ...
1995         23.1           6           3           5           2           0
1996        -34.3           2           3           0           1           3
1997         49.3           2           7           0           0           6
1998          0.4           5           7           3           3           6
1999         -4.4           5           1           6           6           0

[2000 rows x 6 columns]

In [23]:
for i in range(5):
    print(dat_selected[f'p{i+1}_cluster'].unique())

[2 1 3 5 0 6 7]
[3 0 1 5 6 7 2]
[3 1 5 0 6 2 7]
[1 3 0 5 6 2 7 4]
[3 5 1 0 6 7 2 4]


In [26]:
3 + np.nan

nan

In [44]:
total_dummies = pd.DataFrame(np.zeros((dat_selected.shape[0], 8)))
dummies_no4 = pd.DataFrame(np.zeros((dat_selected.shape[0], 8)))
dummies_4 = pd.DataFrame(np.zeros((dat_selected.shape[0], 8)))
for i in range(3):
    dummies_no4 += pd.get_dummies(dat_selected[f'p{i+1}_cluster'], dummy_na=True)

for i in range(2):
    dummies_4 += pd.get_dummies(dat_selected[f'p{i+4}_cluster'], dummy_na=True)

dummies_no4.fillna(0, inplace=True)
total_dummies = dummies_no4 + dummies_4

In [45]:
total_dummies

0    1    2    3    4    5    6    7
0     0.0  1.0  1.0  3.0  0.0  0.0  0.0  0.0
1     1.0  2.0  0.0  1.0  0.0  1.0  0.0  0.0
2     1.0  1.0  0.0  2.0  0.0  1.0  0.0  0.0
3     1.0  2.0  0.0  1.0  0.0  1.0  0.0  0.0
4     0.0  2.0  0.0  2.0  0.0  1.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...
1995  1.0  0.0  1.0  1.0  0.0  1.0  1.0  0.0
1996  1.0  1.0  1.0  2.0  0.0  0.0  0.0  0.0
1997  2.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0
1998  0.0  0.0  0.0  2.0  0.0  1.0  1.0  1.0
1999  1.0  1.0  0.0  0.0  0.0  1.0  2.0  0.0

[2000 rows x 8 columns]

In [46]:
total_dummies.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
dtype: int64

In [54]:
dat_final = pd.concat([dat_selected[' NET_RATING'], total_dummies], axis=1)

In [69]:
dat_final.columns

Index(['net_rating', 0, 1, 2, 3, 4, 5, 6, 7], dtype='object')

In [70]:
dat_final.rename(columns={' NET_RATING': 'net_rating', 0: 'cluster_0', 1: 'cluster_1', 2: 'cluster_2', 3: 'cluster_3', 4: 'cluster_4', 5: 'cluster_5', 6: 'cluster_6', 7: 'cluster_7',}, inplace=True)
dat_final

net_rating  cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  \
0            9.5        0.0        1.0        1.0        3.0        0.0   
1            7.4        1.0        2.0        0.0        1.0        0.0   
2            6.7        1.0        1.0        0.0        2.0        0.0   
3           24.6        1.0        2.0        0.0        1.0        0.0   
4           12.8        0.0        2.0        0.0        2.0        0.0   
...          ...        ...        ...        ...        ...        ...   
1995        23.1        1.0        0.0        1.0        1.0        0.0   
1996       -34.3        1.0        1.0        1.0        2.0        0.0   
1997        49.3        2.0        0.0        1.0        0.0        0.0   
1998         0.4        0.0        0.0        0.0        2.0        0.0   
1999        -4.4        1.0        1.0        0.0        0.0        0.0   

      cluster_5  cluster_6  cluster_7  
0           0.0        0.0        0.0  
1           1.0        0.0        0.0  
2           1.0        0.0        0.0  
3           1.0        0.0        0.0  
4           1.0        0.0        0.0  
...         ...        ...        ...  
1995        1.0        1.0        0.0  
1996        0.0        0.0        0.0  
1997        0.0        1.0        1.0  
1998        1.0        1.0        1.0  
1999        1.0        2.0        0.0  

[2000 rows x 9 columns]

In [76]:
dat_final.describe()

net_rating    cluster_0    cluster_1    cluster_2    cluster_3  \
count  2000.00000  2000.000000  2000.000000  2000.000000  2000.000000   
mean      2.03165     1.398500     0.799500     0.352000     1.155500   
std      25.70921     0.918215     0.699675     0.551587     0.883012   
min    -112.50000     0.000000     0.000000     0.000000     0.000000   
25%     -13.90000     1.000000     0.000000     0.000000     0.750000   
50%       2.70000     1.000000     1.000000     0.000000     1.000000   
75%      18.70000     2.000000     1.000000     1.000000     2.000000   
max      90.30000     5.000000     3.000000     3.000000     4.000000   

         cluster_4    cluster_5    cluster_6    cluster_7  
count  2000.000000  2000.000000  2000.000000  2000.000000  
mean      0.001000     0.607000     0.449000     0.237500  
std       0.031615     0.585425     0.579281     0.528425  
min       0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000  
50%       0.000000     1.000000     0.000000     0.000000  
75%       0.000000     1.000000     1.000000     0.000000  
max       1.000000     2.000000     2.000000     4.000000

## Start with Linear Regression

In [75]:
import statsmodels.formula.api as smf

formula = 'net_rating ~ cluster_0 + cluster_1 + cluster_2 + cluster_3 + cluster_4 + cluster_5 + cluster_6 + cluster_7'
m1 = smf.ols(formula=formula, data = dat_final)
m1_fit = m1.fit()
m1_fit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:             net_rating   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     2.051
Date:                Sun, 05 Mar 2023   Prob (F-statistic):             0.0457
Time:                        22:27:43   Log-Likelihood:                -9323.9
No. Observations:                2000   AIC:                         1.866e+04
Df Residuals:                    1992   BIC:                         1.871e+04
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   5.462e+13   1.69e+14      0.322      0.747   -2.78e+14    3.87e+14
cluster_0  -1.092e+13   3.39e+13     -0.322      0.747   -7.74e+13    5.55e+13
cluster_1  -1.092e+13   3.39e+13     -0.322      0.747   -7.74e+13    5.55e+13
cluster_2  -1.092e+13   3.39e+13     -0.322      0.747   -7.74e+13    5.55e+13
cluster_3  -1.092e+13   3.39e+13     -0.322      0.747   -7.74e+13    5.55e+13
cluster_4  -1.092e+13   3.39e+13     -0.322      0.747   -7.74e+13    5.55e+13
cluster_5  -1.092e+13   3.39e+13     -0.322      0.747   -7.74e+13    5.55e+13
cluster_6  -1.092e+13   3.39e+13     -0.322      0.747   -7.74e+13    5.55e+13
cluster_7  -1.092e+13   3.39e+13     -0.322      0.747   -7.74e+13    5.55e+13
==============================================================================
Omnibus:                       25.646   Durbin-Watson:                   1.989
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               36.288
Skew:                          -0.144   Prob(JB):                     1.32e-08
Kurtosis:                       3.594   Cond. No.                     8.18e+14
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.74e-26. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""